version: "3.8"

services:
  eureka-serviceregistry:
    image: eureka-serviceregistry
    container_name: eureka-serviceregistry
    build: ./eureka
    tty: true
    networks:
      - demo
    ports:
      - "8761:8761"
 
  user-service:
    image: user-service
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8082:8082"
    environment:
      - REGISTRY_HOST=eureka
    depends_on:
      - eureka-serviceregistry
      
  post-service:
    image: post-service
    container_name: post-service
    build:
      context: ./post-service
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka
    depends_on:
      - eureka-serviceregistry
      
  story-service:
    image: story-service
    container_name: story-service
    build:
      context: ./story-service
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8084:8084"
    environment:
      - REGISTRY_HOST=eureka
    depends_on:
      - eureka-serviceregistry
      
  admin-service:
    image: admin-service
    container_name: admin-service
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8085:8085"
    environment:
      - REGISTRY_HOST=eureka
    depends_on:
      - eureka-serviceregistry
  zuul:
    image: zuul
    container_name: zuul
    build: ./zuul
    environment:
      - REGISTRY_HOST=eureka
    tty: true
    networks:
      - demo
    ports:
      - "8086:8086"
    depends_on:
      - eureka-serviceregistry
      - user-service
      - post-service
      - story-service
      - admin-service
networks:
  demo:
    name: demo
    driver: bridge